#ifndef _USERS_JOHAECHANG_OOD_LAB02_PALINDROME_H_
#define _USERS_JOHAECHANG_OOD_LAB02_PALINDROME_H_

int countPalindrome(unsigned int, unsigned int);

#endif  // _USERS_JOHAECHANG_OOD_LAB02_PALINDROME_H_
