# TODO: Set your googletest directory path
GTEST_DIR = /Users/johaechang/googletest/googletest

CPPFLAGS += -isystem $(GTEST_DIR)/include

CXXFLAGS += -pthread --std=c++17

GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# TODO: Set your executable target
all : main

# TODO: Change 'main' and 'main_test' to your executable and test respectively
clean :
	rm -f gtest.a gtest_main.a *.o main test

gtest-all.o : $(GTEST_SRCS_)
	g++ $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	g++ $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

Split.o : Split.h Split.cc
	g++ --std=c++17 -c Split.cc -o $@

Student.o : Student.h Student.cc
	g++ --std=c++17 -c Student.cc -o $@

SwClass.o : SwClass.h Split.h SwClass.cc
	g++ --std=c++17 -c SwClass.cc -o $@

main : main.cc Split.o Student.o SwClass.o $(GTEST_HEADERS)
	g++ --std=c++17 main.cc Split.o Student.o SwClass.o -o $@

# TODO: Change 'calc_test.cc' to your test file
calc_test.o : calc_test.cc $(GTEST_HEADERS)
	g++ $(CPPFLAGS) $(CXXFLAGS) --std=c++17 -c calc_test.cc -o $@

# TODO: Change 'calc_test.o' and 'calc.o' to your object targets
test : calc_test.o calc.o gtest_main.a
	g++ $(CPPFLAGS) $(CXXFLAGS) --std=c++17 $^ -o $@

.PHONY: all clean 
